#!/bin/bash

# Array of ASCII art pieces
ascii_art=(
"  (•_•)\n<(   )>\n  /   \\   — The Debugger"
"  (╯°□°）╯︵ ┻━┻   — Rage Quit"
"  ¯\\_(ツ)_/¯   — It works, somehow"
"  (¬_¬)   — Suspicious Code"
"  (☞ﾟヮﾟ)☞   — Found the bug!"
"  (ᵔᴥᵔ)   — Happy Compiler"
"  (x_x)   — Segmentation Fault"
"  (ಠ_ಠ)   — Linter Disapproves"
"  (ʘ‿ʘ)   — New Feature Activated"
"  (•̀ᴗ•́)و ̑̑   — Code Victory"
"  (•̀ᴗ•́)و ̑̑   — Code Victory"
"  (✧ω✧)   — Bug Squashed!"
"  (づ｡◕‿‿◕｡)づ   — You Got This!"
"  (｡♥‿♥｡)   — Love Your Logic"
"  (＾▽＾)   — Compile Success!"
"  (ง •̀_•́)ง   — Debugging Warrior"
"  (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧   — Feature Unlocked!"
"  (⌐■_■)   — Syntax Master"
"  (☀‿☀)   — Bright Ideas Ahead"
"  (๑˃̵ᴗ˂̵)و   — Mission Accomplished"
"  (≧◡≦)   — Happy Hacker"
"  (๑•̀ㅂ•́)و✧   — Build Complete!"
"  (｡•̀ᴗ-)✧   — Code Like a Pro"
"  (✿◠‿◠)   — Clean Code, Clear Mind"
"  (•‿•)   — Logic Level: Expert"
"  (＾◡＾)   — Terminal Zen"
"  (¬‿¬)   — Clever Commit"
"  (ᵔᴥᵔ)   — Friendly Functions"
"  (☞ﾟヮﾟ)☞   — Found the Fix!"
"  (◕‿◕✿)   — Beautiful Code"
"  (づ￣ ³￣)づ   — Hug from the Compiler"
"  (✧∀✧)   — Refactor Magic"
"  (◠‿◠)   — You’re Crushing It"
"  (•‿•)ノ   — Hello, World!"
"  (＾ω＾)   — Fast & Functional"
"  (ง'̀-'́)ง   — Git It Done!"
"  (✌ﾟ∀ﾟ)☞   — Pull Request Approved"
"  (⌒‿⌒)   — Smooth Deployment"
"  (◕‿◕)   — You’re on Fire!"
"  (•̀o•́)ง   — Test Passed!"
"  (๑˃̵ᴗ˂̵)و   — Code Champion"
"  (✿╹◡╹)   — UI Looks Great!"
"  (＾▽＾)／   — High-Five from the Terminal"
"  (๑•̀‿•́๑)   — Logic Unlocked"
"  (ﾉ´ヮ´)ﾉ*:･ﾟ✧   — You’re Amazing!"
"  (｡•̀ᴗ-)✧   — Keep Pushing Pixels"
"  (≧ω≦)   — You Nailed It!"
"  (◕‿◕)♡   — Code with Heart"
"  (•̀ᴗ•́)و   — One More Line!"
"  (＾ｖ＾)   — You’re Doing Great"
"  (๑˃̵ᴗ˂̵)و   — Victory in Every Commit"
"  (✧‿✧)   — You’re a Wizard, Dev!"
"  (◕‿◕)ノ   — Keep Rocking!"
"  (•̀o•́)ง   — Push with Power"
"  (＾▽＾)   — You’re the MVP!"
"  (⌒▽⌒)☆   — Star Coder"
"  (๑•̀ㅂ•́)و   — Build It Beautiful"
"  (✧◡✧)   — You’re Unstoppable"
"  (◕‿◕✿)   — Code with Confidence"
"  (＾ω＾)ノ   — Keep the Flow Going"
)

# Pick a random index
index=$((RANDOM % ${#ascii_art[@]}))

# Display the art
echo -e "${ascii_art[$index]}"
